### PR TITLE
Allow only a single question for a festival

### LINKED ISSUE #147: Permit only a single question for a festival
Festival questions are questions that are not associated with any artwork. There should be only a single question for a festival. At the moment more than one question can be created for a single festival.

### PR DESCRIPTION
**Pull request by critocrito**
While artworks can have multiple questions festivals are only permitted
to have a single question. This commit enforces this constraint on the
database level by introducing a question type column. The API and the
client are updated to submit the type of the question along with the
question.

Unfortunately this change broke the vote and results unit tests. They
might require a bigger refactor to make them pass again.

closes #147

### CODE REVIEW

**Comment by critocrito** [comment]
@ana0 I enforce the constraint that festivals can have only one question. This aspect works quite well but this change broke the tests for votes and results. I'm a bit lost with those right now, maybe we can take a look at them together?

**Comment by ana0** [comment]
This looks good! Do you mind rebasing with `main` though? The commit history here is looking strange (because of my mistake the other day)

**Comment by critocrito** [comment]
@ana0 I still have the original pull request branch locally on my computer. Should I maybe simply push that one into a new pull request and we close this one?

**Comment by ana0** [comment]
Yup, I think that would do it too!

**Comment by critocrito** [comment]
Created a new pull request in #160. That one is the same as this one, but rebased to main.

**Pull request closed without merging**
