### PR TITLE
Set up booth on emails page

### LINKED ISSUE #136: Email upload encodes vote token
The emails need to include unique vote tokens, signed by a valid booth. The information/functions needed to build a vote token is [here](https://github.com/bitspossessed/culturestake/blob/561c5af5ceb6d57576d31f06dfddc71cf7ec5046/src/common/services/vote.js#L31) 

- [x] It should also be possible to select an organisation to associate these emails with, if an organisation is selected, it should be included in the vote token.
- [x] In the background, the upload email page should create a booth key, and display the button to initialize it. Initializing a booth also involves selecting a festival. If the booth is not initialized, email upload should be disallowed. 
- [x] Vote tokens and associated email addresses should be stored temporarily

### PR DESCRIPTION
**Pull request by ana0**
Closes #136 

This page adds a "create voting booth" snuggle panel to the email upload page. The user must finish initializing the booth before they can use the upload emails form. 

It is possible to select an organisation to associate these emails with, but not required. 
The tasks endpoint has been updated so that additional params are sent with the vote invitation tasks
Vote invitations are stored, to be accessed by view described in [168](https://github.com/bitspossessed/culturestake/issues/168)

### CODE REVIEW

**Comment by critocrito** [comment]
@ana0  I'm trying this PR but have troubles running through the steps. I get an 'invalid data to create booth' error in the UI when I press save but I'm not sure why that is or how I can resolve it. No network request happens; no data validation feedback is given either. Do you know where this one is coming from?

Screen Shot 2021-03-19 at 12 37 47

**Comment by ana0** [comment]
Yes - I wasn't sure what to put in the error message here :thinking: This will come up when the festival isn't ready for voting in some way (no festival question, or festival question has no answers)

**Comment by critocrito** [comment]
Yeah, that change helped a lot and I was able to send vote invitations to the backend. The emails that are actually send don't contain any invitation yet but I believe you are adding those in a separate issue.

I noticed you are using camel case for the name of the vote invitations table that you are adding. It is a little complicated to access camel case table in `psql`. Names are case insensitive in Postgresql (they are just all turned into lowercase by default). One has to use double quotes, not single quotes which are used for literal strings, to access columns and tables . 

Screen Shot 2021-03-19 at 16 43 05

I don't think we can even access the schema due to the camel case naming.

Screen Shot 2021-03-19 at 16 38 21

So I know we already use [camel case](https://sequelize.org/master/manual/naming-strategies.html) all over the place for database fields. But we haven't yet used camel case for any table names. While we probably won't change the existing column names anymore I think we shouldn't start using it for table names going forward. We can even think about starting to use the `underscored` field described above from here on. I'm baffled that the default of Sequelize is to use camel case for columns.

**Comment by critocrito** [comment]
Ahh I just noticed I had a typo in the last screenshot. This works: `psql=# \d "voteInvitations"`

**Comment by ana0** [comment]
Yes, I've also found this a v strange choice on sequelize's part ... I will rename to `invitations`!

**Pull request merged**
