### PR TITLE
Issue 157 create question during festival creation 2

### PR DESCRIPTION
**Pull request by critocrito**
This is the replacement for #162 which I screwed up with an ill fated rebase ...

### CODE REVIEW

**Comment by aeluteia** [comment]
When I try to run this, I get an error when I include an artwork in the creation of a new festival. This appears to not allow the new festival to be created, but on returning to the dashboard it turns out the festival has in fact been created. When creating a new festival without an associated artwork, it works fine. 

Logging out the error, it looks like the new festival-with-artwork is being rejected because the artwork-id already exists. Perhaps it is trying to create a new artwork - in the same way that adding a question at the time of festival creation now creates a new question in the database - rather than just associating the selected, already-existing, artwork with the new festival?

Also, during new festival creation, when adding an artwork that does not already exist (ie has not been created using the 'create new artwork' form, and does not exist on the artworks dashboard), it also works fine, saves the festival, but the artwork does not appear on the artworks dashboard, nor on the 'festival edit' page either. This is perhaps a bit confusing for a user, and maybe we can remove the ability to 'add' an unregistered artwork to a festival in the first place?

**Comment by aeluteia** [comment]
One more small thing - I couldn't start the server initially because in 'src/server/controllers/tasks.js' line 5 needs a tiny typo edit, from 
'import Invitation from '~/server/models/Invitation';' 
to 
'import Invitation from '~/server/models/invitation';'

**Comment by critocrito** [comment]
> When I try to run this, I get an error when I include an artwork in the creation of a new festival. This appears to not allow the new festival to be created, but on returning to the dashboard it turns out the festival has in fact been created. When creating a new festival without an associated artwork, it works fine.
> 
> Logging out the error, it looks like the new festival-with-artwork is being rejected because the artwork-id already exists. Perhaps it is trying to create a new artwork - in the same way that adding a question at the time of festival creation now creates a new question in the database - rather than just associating the selected, already-existing, artwork with the new festival?

Thanks for catching that. I believe I fixed it with the latest commit. Could you give it a try again? Your hunch about why this error occurred was pretty spot on. To create the question inline of the festival model I set the `include` option of `Sequelize.create` to `true`. But this then in turn tried to recreate all associations that were in fact already created. 


> Also, during new festival creation, when adding an artwork that does not already exist (ie has not been created using the 'create new artwork' form, and does not exist on the artworks dashboard), it also works fine, saves the festival, but the artwork does not appear on the artworks dashboard, nor on the 'festival edit' page either. This is perhaps a bit confusing for a user, and maybe we can remove the ability to 'add' an unregistered artwork to a festival in the first place?

Do you mean that one can type into the artwork finder input field anything and then click on `save festival` and you would expect that the artwork will be created along with the festival? I see how that's confusing. It's the same for all other create forms as well I guess.

**Comment by aeluteia** [comment]
> Thanks for catching that. I believe I fixed it with the latest commit. Could you give it a try again? 

Ace, it works great now.

> Do you mean that one can type into the artwork finder input field anything and then click on `save festival` and you would expect that the artwork will be created along with the festival? I see how that's confusing. It's the same for all other create forms as well I guess.

Yes - though I guess I would not expect the artwork to be created there, but instead to be prevented from adding an artwork that hasn't been registered yet. But anyway I think that's a different issue from this - so I reckon this one is ready to merge.

**Comment by ana0** [comment]
So unfortunately I think there's trouble with the FestivalHasOneQuestion relationship between Festivals and Questions ... 

When I create a festival and a festival-question, all works great. Then when I add an artwork to the festival and create an artwork-question, and return the festivals edit page, I see the artwork question.  

I think this association should probably be a FestivalHasManyQuestions, and there are two possibilities regarding display: one would be to keep this ui but filter out the artwork-questions manually, and the other would be to change the question widget in the ui to a table, that shows the festival-questions AND artwork-questions for this festival with a "view" button for each, a bit like the voteweights table

**Comment by critocrito** [comment]
Thanks for finding that one. I did originally thought of the UI to just display the one festival question. It didn't even occur to me to include artwork questions that are part of the festival. Maybe to turn it into a questions table ultimately is nicer for users?

@ana0, @aeluteia, any preference?

**Comment by ana0** [comment]
I agree, I think a table would be a bit nicer to use!

**Comment by aeluteia** [comment]
Yes from me too, it would make the festival edit page comprehensive as well when all the festival-related questions are accessible to set & edit from there.

**Comment by critocrito** [comment]
In it's current form questions and answers can be managed from within the festival details. When creating a new festival it still requires you to already setup a festival question at start. When editing a festival it will show you the questions table and allow you to manage all your questions and add new artwork questions. Note that only artwork questions can be created, since there should be already a festival question and we only want one of those. Any question created from within the festival details will already be associated with that festival. The current `Questions` tab on the admin panel still works as before.

**Comment by ana0** [comment]
Looking good! There's one smaller problem I'm noticing still - which is that the festival page gets into an unusual state if the festival question is deleted, and it can't be repaired by creating a new festival question, since artwork ID is now required on question creation.

I remember discussing question-deletion, but didn't consider this possibility - sorry for not specifying this issue better! The most simple fix I think is probably to make artwork ID not a required field anymore - will merge this and add that one as a new issue!

**Pull request merged**
